FROM python:3.11-alpine

RUN apk add --no-cache g++ gcc libffi-dev musl-dev

WORKDIR /workspace

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "src/train.py" ]
